create table if not exists public.early_access_signups (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.landing_votes (
  id bigint generated by default as identity primary key,
  choice text not null check (choice in ('yes', 'maybe', 'no')),
  created_at timestamptz not null default now()
);

alter table public.early_access_signups enable row level security;
alter table public.landing_votes enable row level security;

create policy "Anyone can add early access signups"
on public.early_access_signups
for insert
to anon
with check (true);

create policy "Anyone can add landing votes"
on public.landing_votes
for insert
to anon
with check (true);

create policy "Anyone can read landing votes"
on public.landing_votes
for select
to anon
using (true);
